Aura/aura-create-and-call-apex-methods/aura-create-and-call-apex-methods/objects/Word_Shuffle__c/Word_Shuffle__c.object-meta.xml
<CustomObject>
    <label>Word Shuffle</label>
    <nameField>
        <displayFormat>Game-{0000}</displayFormat>
        <label>Game Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Word Shuffle</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Apex-Development-Course-main/Aura Framework/aura-data-table/objects/Word_Shuffle__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Aura/aura-create-and-call-apex-methods/aura-create-and-call-apex-methods/objects/Word_Shuffle__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Apex-Development-Course-main/Aura Framework/aura-show-toast-notification/classes/GameResultController.cls
public with sharing class GameResultController {
    @AuraEnabled
    public static List<Word_Shuffle__c> getResults() {
        // get current user's id
        String userId = UserInfo.getUserId();
        List<Word_Shuffle__c> results = [
            SELECT Id, Name, Result__c, Mode__c, CreatedDate
            FROM Word_Shuffle__c
            WHERE CreatedById = :userId
            ORDER BY CreatedDate DESC
        ];
        return results;
    }
}